package br.com.startjob.acesso.core.enumeration;

import java.util.Arrays;

public enum WebPermissao {

    PEDESTRE_VER("WEB_PEDESTRE_VER"),
    PEDESTRE_EDITAR("WEB_PEDESTRE_EDITAR"),
    PEDESTRE_EXCLUIR("WEB_PEDESTRE_EXCLUIR"),
    PEDESTRE_DADOS_SENSIVEIS_VER("WEB_PEDESTRE_DADOS_SENSIVEIS_VER"),
    PEDESTRE_LINK_FACIAL_GERAR("WEB_PEDESTRE_LINK_FACIAL_GERAR"),

    VISITANTE_VER("WEB_VISITANTE_VER"),
    VISITANTE_EDITAR("WEB_VISITANTE_EDITAR"),
    VISITANTE_EXCLUIR("WEB_VISITANTE_EXCLUIR"),

    CADASTRO_ERRO_VER("WEB_CADASTRO_ERRO_VER"),
    APROVACAO_TOTEM_VER("WEB_APROVACAO_TOTEM_VER"),
    APROVACAO_TOTEM_EDITAR("WEB_APROVACAO_TOTEM_EDITAR"),

    CORRESPONDENCIA_VER("WEB_CORRESPONDENCIA_VER"),
    CORRESPONDENCIA_EDITAR("WEB_CORRESPONDENCIA_EDITAR"),

    AVISO_APP_VER("WEB_AVISO_APP_VER"),
    AVISO_APP_EDITAR("WEB_AVISO_APP_EDITAR"),

    TOTEM_AUTO_VER("WEB_TOTEM_AUTO_VER"),
    ALTERACAO_MASSA_VER("WEB_ALTERACAO_MASSA_VER"),
    ALTERACAO_MASSA_EDITAR("WEB_ALTERACAO_MASSA_EDITAR"),

    USUARIO_VER("WEB_USUARIO_VER"),
    USUARIO_EDITAR("WEB_USUARIO_EDITAR"),

    EMPRESA_VER("WEB_EMPRESA_VER"),
    EMPRESA_EDITAR("WEB_EMPRESA_EDITAR"),

    RELATORIO_PEDESTRE_VER("WEB_RELATORIO_PEDESTRE_VER"),
    RELATORIO_VISITANTE_VER("WEB_RELATORIO_VISITANTE_VER"),
    RELATORIO_OCUPACAO_VER("WEB_RELATORIO_OCUPACAO_VER"),
    RELATORIO_LIBERACOES_VER("WEB_RELATORIO_LIBERACOES_VER"),
    RELATORIO_PERMANENCIA_VER("WEB_RELATORIO_PERMANENCIA_VER"),
    RELATORIO_REFEICAO_VER("WEB_RELATORIO_REFEICAO_VER"),
    HISTORICO_ACESSO_VER("WEB_HISTORICO_ACESSO_VER"),

    CONFIG_RHID_VER("WEB_CONFIG_RHID_VER"),
    CONFIG_RHID_EDITAR("WEB_CONFIG_RHID_EDITAR"),
    CONFIG_REGRAS_VER("WEB_CONFIG_REGRAS_VER"),
    CONFIG_REGRAS_EDITAR("WEB_CONFIG_REGRAS_EDITAR"),
    CONFIG_PARAMETROS_VER("WEB_CONFIG_PARAMETROS_VER"),
    CONFIG_PARAMETROS_EDITAR("WEB_CONFIG_PARAMETROS_EDITAR"),
    CONFIG_WEB_PERMISSOES_VER("WEB_CONFIG_WEB_PERMISSOES_VER"),
    CONFIG_WEB_PERMISSOES_EDITAR("WEB_CONFIG_WEB_PERMISSOES_EDITAR"),

    DISPOSITIVO_EQUIPAMENTOS_VER("WEB_DISPOSITIVO_EQUIPAMENTOS_VER"),
    DISPOSITIVO_CAMERAS_VER("WEB_DISPOSITIVO_CAMERAS_VER"),
    DISPOSITIVO_COMANDO_EXECUTAR("WEB_DISPOSITIVO_COMANDO_EXECUTAR"),

    ADMIN_CLIENTES_VER("WEB_ADMIN_CLIENTES_VER"),
    ADMIN_CLIENTES_EDITAR("WEB_ADMIN_CLIENTES_EDITAR"),

    AJUDA_DOWNLOAD_DESKTOP_VER("WEB_AJUDA_DOWNLOAD_DESKTOP_VER");

    private final String codigo;

    WebPermissao(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigo() {
        return codigo;
    }

    public static WebPermissao porCodigo(String codigo) {
        if (codigo == null) {
            return null;
        }
        return Arrays.stream(values())
                .filter(p -> p.codigo.equals(codigo))
                .findFirst()
                .orElse(null);
    }
}
